#!perl

# DATE
# VERSION

# NO_PERINCI_CMDLINE_SCRIPT
# FRAGMENT id=shcompgen-hint completer=1 for=youtube-dl

use 5.010001;
use strict;
use warnings;
use Log::ger;

use CLI::Meta::YoutubeDl;
use Getopt::Long::Complete; # just so we can be detected as Getopt::Long script
use ShellCompleter::Util qw(run_shell_completer_for_getopt_long_app);

my $meta = $CLI::Meta::YoutubeDl::META;
my $opts = $meta->{opts};

binmode(STDOUT, ":encoding(utf8)");
run_shell_completer_for_getopt_long_app(
    map { $_ => (defined $opts->{$_} && defined $opts->{$_}{completion} ? $opts->{$_}{completion} : undef) } keys %$opts,
);

# ABSTRACT: Shell completer for youtube-dl
# PODNAME:

=head1 SYNOPSIS

To install, install the CPAN distribution this command comes in with, and then
in your bash (and/or bash startup file):

 complete -C _youtube-dl youtube-dl

or, you can use L<shcompgen> to do that for you automatically.

Now L<youtube-dl> has bash completion:

 % youtube-dl --no-pl<tab>
 % youtube-dl --external-downloader c<tab>
